/**
 * Normalize a YAML/JSON object so two trees originating from a deep-copy
 * deploy can be compared structurally.
 *
 * What gets normalized:
 *   - All UID-shaped fields → '<UID>' placeholder.
 *     Keys: uid, targetUid, popupTemplateUid, route_id, page_uid, tab_uid,
 *           grid_uid, schema_uid, popup_grid, popup_page, popup_tab,
 *           wrapper, field (when value looks like a UID), parent_uid,
 *           sourceId (template var stays — only literal UIDs replaced),
 *           targetUid (in templateRef), filterByTk (literal UIDs only).
 *   - sortIndex: dropped (deploy-time ordering noise).
 *   - 11-char base36 strings inside arbitrary string values (URLs, JS
 *     references) → '<UID>'. This catches inline references like
 *     `/admin/abc12def345` in link actions.
 *
 * What is preserved:
 *   - File paths (./js/foo.js, templates/popup/x.yaml)
 *   - Template variables ({{ctx.view.inputArgs.filterByTk}})
 *   - All semantic content (titles, types, layouts, fields lists, JS code)
 */

const UID_KEY_NAMES = new Set([
  'uid', 'targetUid', 'popupTemplateUid', 'templateUid',
  'route_id', 'page_uid', 'tab_uid', 'grid_uid', 'schema_uid',
  'popup_grid', 'popup_page', 'popup_tab', 'parent_uid',
  'wrapper', 'field', 'sourceId', 'filterByTk', 'modelUid',
  'host_uid', 'block_uid', 'group_id',
]);

const VOLATILE_KEYS = new Set(['sortIndex', 'spec_hash', 'createdAt', 'updatedAt']);

// Match NocoBase UIDs:
//   - 11-char (most common): generated by uid() utility
//   - 8/9-char (gridSettings layout row ids, some action keys): random hex-ish
//   - 12-char (some legacy)
// All must contain at least one digit AND one letter to avoid matching common
// English words ("definitely", "completion") that happen to be 10+ char a-z.
const UID_PATTERN = /\b(?=[a-z0-9]*\d)(?=[a-z0-9]*[a-z])[a-z0-9]{8,12}\b/g;

function looksLikeUid(value: unknown): boolean {
  if (typeof value !== 'string') return false;
  if (/^\d{10,}$/.test(value)) return true;  // numeric route_id
  if (UID_PATTERN.test(value)) {
    UID_PATTERN.lastIndex = 0;  // reset for /g flag
    return /^[a-z0-9]{8,12}$/.test(value);
  }
  UID_PATTERN.lastIndex = 0;
  return false;
}

function normalizeStringValue(s: string): string {
  // Skip template expressions and file paths — those are semantic.
  if (s.includes('{{')) return s;
  if (s.startsWith('./') || s.startsWith('templates/') || s.startsWith('/admin/')) {
    return s.replace(/\/admin\/[a-z0-9]{8,12}\b/g, '/admin/<UID>');
  }
  // Replace any standalone UIDs in the string. Reset lastIndex due to /g flag.
  UID_PATTERN.lastIndex = 0;
  return s.replace(UID_PATTERN, '<UID>');
}

export function normalize(obj: unknown): unknown {
  if (obj === null || obj === undefined) return obj;
  if (Array.isArray(obj)) return obj.map(normalize);
  if (typeof obj === 'object') {
    const out: Record<string, unknown> = {};
    for (const [k, v] of Object.entries(obj as Record<string, unknown>)) {
      if (VOLATILE_KEYS.has(k)) continue;
      if (UID_KEY_NAMES.has(k)) {
        if (typeof v === 'string') {
          out[k] = looksLikeUid(v) ? '<UID>' : v;
        } else if (typeof v === 'number') {
          out[k] = '<UID>';
        } else {
          out[k] = normalize(v);
        }
        continue;
      }
      out[k] = normalize(v);
    }
    return out;
  }
  if (typeof obj === 'string') return normalizeStringValue(obj);
  return obj;
}

/** Map a `pages/crmcopydiff_main/...` path back to `pages/main/...` so
 * deploy-sync paths line up with source paths for pairing. The prefix is
 * the deploy's group name slugified. We strip any leading slug that ends
 * with `_main`, `_other`, `_lookup` (the standard CRM groups). */
export function unprefixCopyPath(p: string, copyGroupSlug?: string): string {
  if (!copyGroupSlug) return p;
  const re = new RegExp(`(^|/)pages/${copyGroupSlug}_([^/]+)/`);
  return p.replace(re, '$1pages/$2/');
}
