- title: Main
  type: group
  icon: dashboardoutlined
  children:
    - title: Analytics
      icon: areachartoutlined
    - title: Overview
      icon: calendaroutlined
    - title: Leads
      icon: useraddoutlined
    - title: Customers
      icon: teamoutlined
    - title: Opportunities
      icon: fundoutlined
    - title: Products
      icon: appstoreoutlined
    - title: Orders
      icon: shoppingcartoutlined
    - title: More Charts
      type: group
      children:
        - title: Executive
          icon: crownoutlined
        - title: SalesRep
          icon: solutionoutlined
        - title: SalesManager
          icon: useroutlined
- title: Lookup
  icon: monitoroutlined
- title: Other
  type: group
  icon: appstoreaddoutlined
  children:
    - title: Contacts
      icon: usergroupaddoutlined
    - title: Activity
      icon: orderedlistoutlined
    - title: Exchange Rate
      icon: dollaroutlined
    - title: Stage Settings
      icon: apartmentoutlined
    - title: Emails
      icon: mailoutlined
    - title: Data Analysis
      icon: compassoutlined
