title: CRM System Demo Date Shift
type: schedule
enabled: true
key: ent9831jh17
options:
  stackLimit: 1
  deleteExecutionOnStatus: []
trigger:
  mode: 0
  repeat: 86400000
  startsOn: '2026-01-24T16:00:00.000Z'
graph:
  - sql_action
nodes:
  sql_action:
    type: sql
    title: SQL action
    config:
      $ref: components/sql_action.yaml
